### ISSUE TITLE
Changing focus removes data from other fields

### ISSUE THREAD

**Issue by nicomfe** [itaylor/redux-form-immutablejs-example#1]
So if you add more than one field to the form , when you change focus between fields, the data you already typed in the previous field gets removed.

**Comment by itaylor** [comment]
There are two ways to fix this issue.  One is to allow the 'form' key in your immutable state object to have a normal JS object value and not convert it to immutable.  That's perhaps the simplest approach and can be seen in https://github.com/itaylor/redux-form-immutablejs-example/commit/e7fc46d265422772e08aeec891418c9c7facf448.

The other way is to .toJS the state on the way into the reducer and .fromJS on the way out.    This can be seen in https://github.com/itaylor/redux-form-immutablejs-example/commit/aed69a19a8efd51f4dcb83931ddc4d6d93ad7f53

I've chosen to include the second way in the master branch, because it preserves your whole state object as an immutablejs object.  Which I think is likely what most people would want.

FYI, in my real project I use my own custom root reducer (not redux-immutablejs) and allow the redux form object to be a normal JS object inside of the immutable root object, saving the redundant calls to fromJS and toJS.
